apiVersion: v1
kind: Service
metadata:
  name: mnemo-service
spec:
  type: LoadBalancer
  selector:
    app: mnemo
  ports:
  - port: {{ .Values.mnemo.api.port }}
    targetPort: {{ .Values.mnemo.api.port }}